name: CI - Culinaria Store

on:
  push:
    branches: [ main, feature/frontend ]
  pull_request:
    branches: [ main ]

jobs:
  build-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3

      - name: Instalar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Instalar dependencias del frontend
        working-directory: ./frontend
        run: npm install

      - name: Compilar frontend
        working-directory: ./frontend
        run: npm run build

  build-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3

      - name: Instalar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Instalar dependencias del backend
        working-directory: ./backend
        run: npm install